### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by SyCoQc** [black-ops-drivers/control4-myq#15] opened 2024-01-01 13:55 UTC
Hello, wanted to try your Control4 driver but getting the following error:

_lun. 01 janv. 2024 08:51:47 EST [ERROR]: Authentication failed; HTTP POST request to https://partner-identity.myq-cloud.com/connect/token failed with status code 401_

btw I've re-connected with MyQ app to confirm my credentials are goods and it's working within the App...

Maybe API changed again ?

Thank You for your help :-)

**Comment by black-ops-drivers** [comment] 2024-01-02 16:04
Duplicate of #11

**Closed by black-ops-drivers** 2024-01-02 16:04 UTC
