### ISSUE TITLE
MYQ Login Issue for Control4

### ISSUE THREAD

**Issue by 323empress** [black-ops-drivers/control4-myq#14] opened 2023-12-12 03:53 UTC
Hi there,
I tried many times to login to MYQ account but there is a problem, do you think this driver is working properly?
Here is some screen shots from the errors.
Please help me to solve the issue.
Looking forward to your respond
Thank you
![Screenshot 2023-12-11 224744](https://github.com/black-ops-drivers/control4-myq/assets/153048901/2aafd7ea-ea22-40c4-822c-db58472dd2a3)
![Screenshot 2023-12-11 224524](https://github.com/black-ops-drivers/control4-myq/assets/153048901/a3bd6f9d-9f66-4405-97cc-9973c49f10b4)
![Screenshot 2023-12-11 223808](https://github.com/black-ops-drivers/control4-myq/assets/153048901/c7e7ac38-ba26-4fd3-b45f-cae6df97f4ce)

**Comment by black-ops-drivers** [comment] 2023-12-12 04:01
Duplicate of #11

**Closed by black-ops-drivers** 2023-12-12 04:01 UTC
